server:
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
  port: 8080
  error:
    include-stacktrace: never

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: roundrobin_user
    password: C1qMXX6Mop1Yx514ItG63C2LdZ3Xj9Ka
    url: jdbc:postgresql://dpg-ckvdpsub0mos73912ih0-a.frankfurt-postgres.render.com:5432/roundrobin
    liquibase:
      change-log: db/db.changelog-master.xml
      default-schema: public
      liquibase-schema: public
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create-drop
      database-platform: org.hibernate.dialect.PostgreSQLDialect